services:

  # 1. Tu servicio de Backend con FastAPI
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reto01-backend
    ports:
      - "8000:8000"
    environment:
      - SQLITE_DATABASE=/app/backend/database/sqlite_reto.db
      - ORACLE_HOST=oracle
      - ORACLE_PORT=1521
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      # Persistencia de SQLite: mapea la carpeta de tu ordenador a la del contenedor
      - ./backend/database:/app/backend/database
    depends_on:
      oracle:
        condition: service_healthy

  oracle:
    image: gvenzl/oracle-free:latest
    container_name: reto01-oracle

    ports:
      - "1521:1521"

    environment:
      ORACLE_PASSWORD: ${ORACLE_ADMIN_PASSWORD}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}

    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 20

  mariadb:
    image: mariadb:11.8
    container_name: reto01-mariadb

    ports:
      - "3306:3306"

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped
volumes:
  oracle_data:
  mariadb_data: